export interface Task {
  id?: string; // Optional ID, will be generated by MongoDB
  title: string;
  description?: string; // Optional description
  dueDate: Date;
  status: 'To-Do' | 'In Progress' | 'Done';
  priority?: 'Low' | 'Medium' | 'High'; // Optional priority (for the bonus feature)
}